module.exports.errorMessages = {
  movieConflict: 'Фильм с таким id уже добавлен в базу пользователя',
  validError: 'Переданы некорректные данные',
  movieNotFound: 'Фильм с указанным id не найден в базе пользователя',
  movieInvalidId: 'Неверный идентификатор фильма',
  emptyPass: 'Пароль не может быть пустым',
  userConflict: 'Пользователь с таким email уже существует',
  incorrectLogin: 'Неправильные почта или пароль',
  userNotFound: 'Пользователь не найден',
  userInvalidId: 'Неверный идентификатор пользователя',
  unauthorized: 'Необходима авторизация',
  urlNotFound: 'Неверный адрес запроса',
  serverError: 'На сервере произошла ошибка',
  emptyEmail: 'поле email не может быть пустым',
  invalidEmail: 'Вы ввели невалидный email',
  emailNoString: 'Поле email должно быть строкой',
  passNoString: 'Пароль должен быть строкой',
  anyRequired: 'Поле {#label} обязательно',
  nameEmpty: 'Имя не может быть пустым',
  nameMin: 'Минимальная длина имени - 2 символа',
  nameMax: 'Максимальная длина имени - 30 символов',
  nameNoString: 'Имя должно быть строкой',
  anyNoUrl: 'В поле {#label} передана невалидная ссылка',
  anyEmpty: 'Поле {#label} не может быть пустым',
  anyNoString: 'Поле {#label} дожно быть строкой',
  anyNoNumber: 'Поле {#label} должно быть числовым',
};

module.exports.messages = {
  logout: 'Выход выполнен',
  auth: 'Авторизация успешна',
};
